-- Generado por scripts/db/permisos-seed.ts (pnpm db:permisos) desde src/lib/auth/permisos.ts — no editar.
-- Idempotente: upsert del catálogo y sincronización de los permisos por defecto de los roles de sistema.

insert into public.permisos (clave, modulo, descripcion, es_sensible, orden) values
  ('inicio.admin', 'inicio', 'Ver el panel de inicio administrativo', false, 1),
  ('inicio.anunciante', 'inicio', 'Ver el panel de inicio del anunciante', false, 2),
  ('inicio.medio', 'inicio', 'Ver el panel de inicio del medio', false, 3),
  ('analitica.global', 'analitica', 'Ver analítica agregada de toda la plataforma', false, 4),
  ('analitica.mapa', 'analitica', 'Usar el explorador geográfico', false, 5),
  ('reportes.ver', 'reportes', 'Consultar reportes (el anunciante solo ve los suyos)', false, 6),
  ('reportes.exportar', 'reportes', 'Exportar reportes a Excel y PDF', false, 7),
  ('reportes.finanzas', 'reportes', 'Ver reportes financieros y de cartera', false, 8),
  ('usuarios.ver', 'usuarios', 'Ver el listado y la ficha de usuarios', false, 9),
  ('usuarios.invitar', 'usuarios', 'Invitar usuarios y regenerar invitaciones', true, 10),
  ('usuarios.editar', 'usuarios', 'Editar datos, rol y organización de usuarios', true, 11),
  ('usuarios.suspender', 'usuarios', 'Suspender y reactivar usuarios', true, 12),
  ('usuarios.cerrar_sesiones', 'usuarios', 'Cerrar las sesiones activas de otro usuario', true, 13),
  ('usuarios.generar_enlace', 'usuarios', 'Generar enlaces de recuperación de contraseña', true, 14),
  ('usuarios.eliminar', 'usuarios', 'Desactivar usuarios definitivamente', true, 15),
  ('roles.ver', 'roles', 'Ver roles y sus permisos', false, 16),
  ('roles.gestionar', 'roles', 'Crear, editar y eliminar roles personalizados', true, 17),
  ('auditoria.ver', 'auditoria', 'Consultar la bitácora de auditoría', false, 18),
  ('auditoria.exportar', 'auditoria', 'Exportar la bitácora', false, 19),
  ('accesos.ver', 'accesos', 'Consultar el registro de accesos y su mapa', false, 20),
  ('accesos.exportar', 'accesos', 'Exportar el registro de accesos', false, 21),
  ('configuracion.ver', 'configuracion', 'Ver parámetros de la plataforma', false, 22),
  ('configuracion.editar', 'configuracion', 'Editar parámetros generales y niveles de verificación', true, 23),
  ('configuracion.tarifas', 'configuracion', 'Programar nuevas vigencias de tarifas', true, 24),
  ('configuracion.comisiones', 'configuracion', 'Editar la comisión global y sus excepciones', true, 25),
  ('configuracion.tributario', 'configuracion', 'Editar parámetros tributarios y resoluciones DIAN', true, 26),
  ('configuracion.catalogos', 'configuracion', 'Editar sectores, categorías, franjas, formatos, plantillas y términos', false, 27),
  ('datos_sensibles.ver', 'datos_sensibles', 'Revelar datos personales, documentos de identidad y datos bancarios (uno por uno, con bitácora)', true, 28),
  ('datos_sensibles.editar', 'datos_sensibles', 'Corregir datos personales o bancarios de terceros', true, 29),
  ('medios.ver', 'medios', 'Ver medios y sus fichas', false, 30),
  ('medios.editar', 'medios', 'Editar la ficha de cualquier medio', false, 31),
  ('medios.verificar', 'medios', 'Verificar medios, documentos y cuentas sociales (incluidas las reverificaciones)', false, 32),
  ('medios.suspender', 'medios', 'Suspender y reactivar medios', true, 33),
  ('medios.clasificar_pertinencia', 'medios', 'Clasificar la pertinencia geográfica de medios', false, 34),
  ('medios.editar_propio', 'medios', 'Editar el perfil, cuentas y documentos del propio medio', false, 35),
  ('anunciantes.ver', 'anunciantes', 'Ver anunciantes y sus fichas', false, 36),
  ('anunciantes.editar', 'anunciantes', 'Crear y editar anunciantes', false, 37),
  ('anunciantes.verificar', 'anunciantes', 'Verificar anunciantes y sus documentos', false, 38),
  ('anunciantes.suspender', 'anunciantes', 'Suspender y reactivar anunciantes', true, 39),
  ('anunciantes.editar_propio', 'anunciantes', 'Editar los datos de la propia empresa', false, 40),
  ('campanas.ver', 'campanas', 'Ver todas las campañas', false, 41),
  ('campanas.gestionar', 'campanas', 'Crear y gestionar campañas por cuenta de un anunciante', false, 42),
  ('campanas.gestionar_propias', 'campanas', 'Crear y gestionar las campañas propias', false, 43),
  ('ofertas.ver', 'ofertas', 'Ver todas las ofertas', false, 44),
  ('ofertas.gestionar', 'ofertas', 'Crear y editar ofertas por cuenta de un anunciante', false, 45),
  ('ofertas.moderar', 'ofertas', 'Moderar ofertas (publicar, devolver, rechazar, cancelar)', false, 46),
  ('ofertas.gestionar_propias', 'ofertas', 'Crear, enviar a revisión y cancelar ofertas propias', false, 47),
  ('ofertas.marketplace', 'ofertas', 'Ver el marketplace de ofertas elegibles', false, 48),
  ('ofertas.aceptar', 'ofertas', 'Aceptar o rechazar ofertas', false, 49),
  ('asignaciones.ver', 'asignaciones', 'Ver todas las asignaciones', false, 50),
  ('asignaciones.gestionar', 'asignaciones', 'Cancelar asignaciones', true, 51),
  ('asignaciones.ver_propias', 'asignaciones', 'Ver las asignaciones propias', false, 52),
  ('asignaciones.ejecutar', 'asignaciones', 'Descargar contenido, cargar evidencia y métricas', false, 53),
  ('evidencias.validar', 'evidencias', 'Validar o rechazar evidencias de publicación', false, 54),
  ('metricas.validar', 'metricas', 'Validar o rechazar métricas', false, 55),
  ('metricas.editar_validadas', 'metricas', 'Corregir métricas ya validadas', true, 56),
  ('liquidaciones.ver', 'liquidaciones', 'Ver todas las liquidaciones', false, 57),
  ('liquidaciones.generar', 'liquidaciones', 'Generar cortes de liquidación', false, 58),
  ('liquidaciones.aprobar', 'liquidaciones', 'Aprobar o anular liquidaciones y documentos soporte', true, 59),
  ('liquidaciones.registrar_pago', 'liquidaciones', 'Registrar el pago de liquidaciones con soporte', true, 60),
  ('liquidaciones.ver_propias', 'liquidaciones', 'Ver las liquidaciones y ganancias propias', false, 61),
  ('facturas.ver', 'facturas', 'Ver todas las facturas', false, 62),
  ('facturas.gestionar', 'facturas', 'Crear, emitir y anular facturas', true, 63),
  ('facturas.ver_propias', 'facturas', 'Ver las facturas propias', false, 64),
  ('pagos.registrar', 'pagos', 'Registrar pagos de anunciantes', true, 65),
  ('disputas.ver', 'disputas', 'Ver todas las disputas', false, 66),
  ('disputas.abrir', 'disputas', 'Abrir disputas sobre asignaciones', false, 67),
  ('disputas.resolver', 'disputas', 'Resolver o descartar disputas', true, 68),
  ('notificaciones.ver', 'notificaciones', 'Ver y marcar las notificaciones propias', false, 69),
  ('cuenta.gestionar', 'cuenta', 'Gestionar el perfil, la seguridad y las preferencias propias', false, 70)
on conflict (clave) do update set
  modulo = excluded.modulo,
  descripcion = excluded.descripcion,
  es_sensible = excluded.es_sensible,
  orden = excluded.orden;

with por_defecto (rol_clave, permiso_clave) as (values
  ('SUPERADMIN', 'inicio.admin'),
  ('ADMIN', 'inicio.admin'),
  ('OPERACIONES', 'inicio.admin'),
  ('FINANZAS', 'inicio.admin'),
  ('SUPERADMIN', 'inicio.anunciante'),
  ('ANUNCIANTE', 'inicio.anunciante'),
  ('SUPERADMIN', 'inicio.medio'),
  ('MEDIO', 'inicio.medio'),
  ('SUPERADMIN', 'analitica.global'),
  ('ADMIN', 'analitica.global'),
  ('OPERACIONES', 'analitica.global'),
  ('FINANZAS', 'analitica.global'),
  ('SUPERADMIN', 'analitica.mapa'),
  ('ADMIN', 'analitica.mapa'),
  ('OPERACIONES', 'analitica.mapa'),
  ('FINANZAS', 'analitica.mapa'),
  ('SUPERADMIN', 'reportes.ver'),
  ('ADMIN', 'reportes.ver'),
  ('OPERACIONES', 'reportes.ver'),
  ('FINANZAS', 'reportes.ver'),
  ('ANUNCIANTE', 'reportes.ver'),
  ('SUPERADMIN', 'reportes.exportar'),
  ('ADMIN', 'reportes.exportar'),
  ('OPERACIONES', 'reportes.exportar'),
  ('FINANZAS', 'reportes.exportar'),
  ('ANUNCIANTE', 'reportes.exportar'),
  ('SUPERADMIN', 'reportes.finanzas'),
  ('ADMIN', 'reportes.finanzas'),
  ('FINANZAS', 'reportes.finanzas'),
  ('SUPERADMIN', 'usuarios.ver'),
  ('ADMIN', 'usuarios.ver'),
  ('OPERACIONES', 'usuarios.ver'),
  ('SUPERADMIN', 'usuarios.invitar'),
  ('ADMIN', 'usuarios.invitar'),
  ('SUPERADMIN', 'usuarios.editar'),
  ('ADMIN', 'usuarios.editar'),
  ('SUPERADMIN', 'usuarios.suspender'),
  ('ADMIN', 'usuarios.suspender'),
  ('SUPERADMIN', 'usuarios.cerrar_sesiones'),
  ('ADMIN', 'usuarios.cerrar_sesiones'),
  ('SUPERADMIN', 'usuarios.generar_enlace'),
  ('ADMIN', 'usuarios.generar_enlace'),
  ('SUPERADMIN', 'usuarios.eliminar'),
  ('SUPERADMIN', 'roles.ver'),
  ('ADMIN', 'roles.ver'),
  ('SUPERADMIN', 'roles.gestionar'),
  ('SUPERADMIN', 'auditoria.ver'),
  ('ADMIN', 'auditoria.ver'),
  ('SUPERADMIN', 'auditoria.exportar'),
  ('ADMIN', 'auditoria.exportar'),
  ('SUPERADMIN', 'accesos.ver'),
  ('ADMIN', 'accesos.ver'),
  ('SUPERADMIN', 'accesos.exportar'),
  ('ADMIN', 'accesos.exportar'),
  ('SUPERADMIN', 'configuracion.ver'),
  ('ADMIN', 'configuracion.ver'),
  ('OPERACIONES', 'configuracion.ver'),
  ('FINANZAS', 'configuracion.ver'),
  ('SUPERADMIN', 'configuracion.editar'),
  ('ADMIN', 'configuracion.editar'),
  ('SUPERADMIN', 'configuracion.tarifas'),
  ('ADMIN', 'configuracion.tarifas'),
  ('SUPERADMIN', 'configuracion.comisiones'),
  ('ADMIN', 'configuracion.comisiones'),
  ('SUPERADMIN', 'configuracion.tributario'),
  ('ADMIN', 'configuracion.tributario'),
  ('FINANZAS', 'configuracion.tributario'),
  ('SUPERADMIN', 'configuracion.catalogos'),
  ('ADMIN', 'configuracion.catalogos'),
  ('SUPERADMIN', 'datos_sensibles.ver'),
  ('ADMIN', 'datos_sensibles.ver'),
  ('OPERACIONES', 'datos_sensibles.ver'),
  ('FINANZAS', 'datos_sensibles.ver'),
  ('SUPERADMIN', 'datos_sensibles.editar'),
  ('ADMIN', 'datos_sensibles.editar'),
  ('SUPERADMIN', 'medios.ver'),
  ('ADMIN', 'medios.ver'),
  ('OPERACIONES', 'medios.ver'),
  ('FINANZAS', 'medios.ver'),
  ('SUPERADMIN', 'medios.editar'),
  ('ADMIN', 'medios.editar'),
  ('OPERACIONES', 'medios.editar'),
  ('SUPERADMIN', 'medios.verificar'),
  ('ADMIN', 'medios.verificar'),
  ('OPERACIONES', 'medios.verificar'),
  ('SUPERADMIN', 'medios.suspender'),
  ('ADMIN', 'medios.suspender'),
  ('OPERACIONES', 'medios.suspender'),
  ('SUPERADMIN', 'medios.clasificar_pertinencia'),
  ('ADMIN', 'medios.clasificar_pertinencia'),
  ('OPERACIONES', 'medios.clasificar_pertinencia'),
  ('SUPERADMIN', 'medios.editar_propio'),
  ('MEDIO', 'medios.editar_propio'),
  ('SUPERADMIN', 'anunciantes.ver'),
  ('ADMIN', 'anunciantes.ver'),
  ('OPERACIONES', 'anunciantes.ver'),
  ('FINANZAS', 'anunciantes.ver'),
  ('SUPERADMIN', 'anunciantes.editar'),
  ('ADMIN', 'anunciantes.editar'),
  ('OPERACIONES', 'anunciantes.editar'),
  ('SUPERADMIN', 'anunciantes.verificar'),
  ('ADMIN', 'anunciantes.verificar'),
  ('OPERACIONES', 'anunciantes.verificar'),
  ('SUPERADMIN', 'anunciantes.suspender'),
  ('ADMIN', 'anunciantes.suspender'),
  ('SUPERADMIN', 'anunciantes.editar_propio'),
  ('ANUNCIANTE', 'anunciantes.editar_propio'),
  ('SUPERADMIN', 'campanas.ver'),
  ('ADMIN', 'campanas.ver'),
  ('OPERACIONES', 'campanas.ver'),
  ('FINANZAS', 'campanas.ver'),
  ('SUPERADMIN', 'campanas.gestionar'),
  ('ADMIN', 'campanas.gestionar'),
  ('OPERACIONES', 'campanas.gestionar'),
  ('SUPERADMIN', 'campanas.gestionar_propias'),
  ('ANUNCIANTE', 'campanas.gestionar_propias'),
  ('SUPERADMIN', 'ofertas.ver'),
  ('ADMIN', 'ofertas.ver'),
  ('OPERACIONES', 'ofertas.ver'),
  ('FINANZAS', 'ofertas.ver'),
  ('SUPERADMIN', 'ofertas.gestionar'),
  ('ADMIN', 'ofertas.gestionar'),
  ('OPERACIONES', 'ofertas.gestionar'),
  ('SUPERADMIN', 'ofertas.moderar'),
  ('ADMIN', 'ofertas.moderar'),
  ('OPERACIONES', 'ofertas.moderar'),
  ('SUPERADMIN', 'ofertas.gestionar_propias'),
  ('ANUNCIANTE', 'ofertas.gestionar_propias'),
  ('SUPERADMIN', 'ofertas.marketplace'),
  ('MEDIO', 'ofertas.marketplace'),
  ('SUPERADMIN', 'ofertas.aceptar'),
  ('MEDIO', 'ofertas.aceptar'),
  ('SUPERADMIN', 'asignaciones.ver'),
  ('ADMIN', 'asignaciones.ver'),
  ('OPERACIONES', 'asignaciones.ver'),
  ('FINANZAS', 'asignaciones.ver'),
  ('SUPERADMIN', 'asignaciones.gestionar'),
  ('ADMIN', 'asignaciones.gestionar'),
  ('OPERACIONES', 'asignaciones.gestionar'),
  ('SUPERADMIN', 'asignaciones.ver_propias'),
  ('ANUNCIANTE', 'asignaciones.ver_propias'),
  ('MEDIO', 'asignaciones.ver_propias'),
  ('SUPERADMIN', 'asignaciones.ejecutar'),
  ('MEDIO', 'asignaciones.ejecutar'),
  ('SUPERADMIN', 'evidencias.validar'),
  ('ADMIN', 'evidencias.validar'),
  ('OPERACIONES', 'evidencias.validar'),
  ('SUPERADMIN', 'metricas.validar'),
  ('ADMIN', 'metricas.validar'),
  ('OPERACIONES', 'metricas.validar'),
  ('SUPERADMIN', 'metricas.editar_validadas'),
  ('ADMIN', 'metricas.editar_validadas'),
  ('SUPERADMIN', 'liquidaciones.ver'),
  ('ADMIN', 'liquidaciones.ver'),
  ('FINANZAS', 'liquidaciones.ver'),
  ('SUPERADMIN', 'liquidaciones.generar'),
  ('ADMIN', 'liquidaciones.generar'),
  ('FINANZAS', 'liquidaciones.generar'),
  ('SUPERADMIN', 'liquidaciones.aprobar'),
  ('ADMIN', 'liquidaciones.aprobar'),
  ('FINANZAS', 'liquidaciones.aprobar'),
  ('SUPERADMIN', 'liquidaciones.registrar_pago'),
  ('FINANZAS', 'liquidaciones.registrar_pago'),
  ('SUPERADMIN', 'liquidaciones.ver_propias'),
  ('MEDIO', 'liquidaciones.ver_propias'),
  ('SUPERADMIN', 'facturas.ver'),
  ('ADMIN', 'facturas.ver'),
  ('FINANZAS', 'facturas.ver'),
  ('SUPERADMIN', 'facturas.gestionar'),
  ('FINANZAS', 'facturas.gestionar'),
  ('SUPERADMIN', 'facturas.ver_propias'),
  ('ANUNCIANTE', 'facturas.ver_propias'),
  ('SUPERADMIN', 'pagos.registrar'),
  ('FINANZAS', 'pagos.registrar'),
  ('SUPERADMIN', 'disputas.ver'),
  ('ADMIN', 'disputas.ver'),
  ('OPERACIONES', 'disputas.ver'),
  ('FINANZAS', 'disputas.ver'),
  ('SUPERADMIN', 'disputas.abrir'),
  ('ADMIN', 'disputas.abrir'),
  ('OPERACIONES', 'disputas.abrir'),
  ('ANUNCIANTE', 'disputas.abrir'),
  ('MEDIO', 'disputas.abrir'),
  ('SUPERADMIN', 'disputas.resolver'),
  ('ADMIN', 'disputas.resolver'),
  ('OPERACIONES', 'disputas.resolver'),
  ('SUPERADMIN', 'notificaciones.ver'),
  ('ADMIN', 'notificaciones.ver'),
  ('OPERACIONES', 'notificaciones.ver'),
  ('FINANZAS', 'notificaciones.ver'),
  ('ANUNCIANTE', 'notificaciones.ver'),
  ('MEDIO', 'notificaciones.ver'),
  ('SUPERADMIN', 'cuenta.gestionar'),
  ('ADMIN', 'cuenta.gestionar'),
  ('OPERACIONES', 'cuenta.gestionar'),
  ('FINANZAS', 'cuenta.gestionar'),
  ('ANUNCIANTE', 'cuenta.gestionar'),
  ('MEDIO', 'cuenta.gestionar')
), retirados as (
  delete from public.rol_permisos rp
  using public.roles r
  where r.id = rp.rol_id and r.es_sistema
    and not exists (select 1 from por_defecto d
                    where d.rol_clave = r.clave and d.permiso_clave = rp.permiso_clave)
)
insert into public.rol_permisos (rol_id, permiso_clave)
select r.id, d.permiso_clave
from por_defecto d
join public.roles r on r.clave = d.rol_clave and r.es_sistema
on conflict (rol_id, permiso_clave) do nothing;
