import { describe, expect, it } from "vitest"

import { urlDeDatosSvg } from "./qr"

const SVG = '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="#000"/></svg>'

describe("urlDeDatosSvg", () => {
  it("codifica el SVG que entrega auth-js", () => {
    const url = urlDeDatosSvg(`data:image/svg+xml;utf-8,${SVG}`)
    expect(url.startsWith("data:image/svg+xml;charset=utf-8,")).toBe(true)
    expect(url).not.toContain("#")
    expect(decodeURIComponent(url.split(",")[1])).toBe(SVG)
  })

  it("admite la declaración XML y el comentario que antepone Supabase", () => {
    const conDeclaracion = `<?xml version="1.0"?>\n<!-- Generated by SVGo -->\n${SVG}`
    const url = urlDeDatosSvg(`data:image/svg+xml;utf-8,${conDeclaracion}`)
    expect(decodeURIComponent(url.split(",")[1])).toBe(conDeclaracion)
  })

  it("acepta el SVG sin prefijo", () => {
    expect(decodeURIComponent(urlDeDatosSvg(SVG).split(",")[1])).toBe(SVG)
  })

  it("rechaza contenido que no es SVG", () => {
    expect(() => urlDeDatosSvg("data:text/html,<script>")).toThrow()
  })
})
