-- Migración 2 (parte) · geo_semilla_paises_1 — países A–L de supabase/seed/geo.sql
-- (pnpm geo:build), filas sin cambios; separado de `geo` por tamaño.

insert into public.paises (iso2, iso3, numerico, nombre, nombre_normalizado, alias, continente, subregion, con_geometria, lon, lat) values
  ('AD', 'AND', '020', 'Andorra', 'andorra', array['principado de andorra', 'principality of andorra', 'principat dandorra']::text[], 'Europa', 'Europa meridional', false, 1.5, 42.5),
  ('AE', 'ARE', '784', 'Emiratos Árabes Unidos', 'emiratos arabes unidos', array['eau', 'emirates', 'emiratos', 'emiratos arabes', 'uae', 'united arab emirates']::text[], 'Asia', 'Asia occidental', true, 54.4916, 23.5094),
  ('AF', 'AFG', '004', 'Afganistán', 'afganistan', array['afghanistan', 'islamic republic of afghanistan', 'islamic state of afghanistan', 'republica islamica de afganistan']::text[], 'Asia', 'Asia meridional', true, 66.0767, 33.8565),
  ('AG', 'ATG', '028', 'Antigua y Barbuda', 'antigua y barbuda', array['antigua and barbuda']::text[], 'América', 'Caribe', false, -61.8, 17.05),
  ('AI', 'AIA', '660', 'Anguila', 'anguila', array['anguilla']::text[], 'América', 'Caribe', false, -63.1667, 18.25),
  ('AL', 'ALB', '008', 'Albania', 'albania', array['republic of albania', 'republica de albania', 'shqiperi', 'shqiperia', 'shqipnia']::text[], 'Europa', 'Europa meridional', true, 20.0002, 41.13),
  ('AM', 'ARM', '051', 'Armenia', 'armenia', array['hayastan', 'republic of armenia', 'republica de armenia']::text[], 'Asia', 'Asia occidental', true, 45.0357, 40.3058),
  ('AO', 'AGO', '024', 'Angola', 'angola', array['peoples republic of angola', 'republic of angola', 'republica de angola']::text[], 'África', 'África central', true, 17.5135, -12.2995),
  ('AQ', 'ATA', '010', 'Antártida', 'antartida', array['antarctica']::text[], 'Antártida', null, true, 43.418, -79.3308),
  ('AR', 'ARG', '032', 'Argentina', 'argentina', array['argentine republic', 'republica argentina']::text[], 'América', 'América del Sur', true, -64.4442, -33.8823),
  ('AS', 'ASM', '016', 'Samoa Americana', 'samoa americana', array['amelika samoa', 'american samoa', 'amerika samoa', 'samoa amelika']::text[], 'Oceanía', 'Polinesia', false, -170, -14.3333),
  ('AT', 'AUT', '040', 'Austria', 'austria', array['oesterreich', 'osterreich', 'republic of austria', 'republica de austria']::text[], 'Europa', 'Europa occidental', true, 14.116, 47.5523),
  ('AU', 'AUS', '036', 'Australia', 'australia', array['commonwealth of australia', 'mancomunidad de australia']::text[], 'Oceanía', 'Australia y Nueva Zelanda', true, 134.7762, -24.5773),
  ('AW', 'ABW', '533', 'Aruba', 'aruba', '{}', 'América', 'Caribe', false, -69.9667, 12.5),
  ('AX', 'ALA', '248', 'Islas Åland', 'islas aland', array['aaland', 'ahvenanmaa', 'aland', 'aland islands', 'alandia']::text[], 'Europa', 'Europa septentrional', false, 19.9, 60.1167),
  ('AZ', 'AZE', '031', 'Azerbaiyán', 'azerbaiyan', array['azerbaijan', 'republic of azerbaijan', 'republica de azerbaiyan']::text[], 'Asia', 'Asia occidental', true, 47.2004, 40.3037),
  ('BA', 'BIH', '070', 'Bosnia y Herzegovina', 'bosnia y herzegovina', array['bosnia and herz', 'bosnia and herzegovina', 'bosnia herzegovina']::text[], 'Europa', 'Europa meridional', true, 17.7877, 44.175),
  ('BB', 'BRB', '052', 'Barbados', 'barbados', '{}', 'América', 'Caribe', false, -59.5333, 13.1667),
  ('BD', 'BGD', '050', 'Bangladés', 'banglades', array['bangladesh', 'gonoprojatontri bangladesh', 'peoples republic of bangladesh', 'republica popular de bangladesh']::text[], 'Asia', 'Asia meridional', true, 90.0655, 23.8887),
  ('BE', 'BEL', '056', 'Bélgica', 'belgica', array['belgie', 'belgien', 'belgique', 'belgium', 'kingdom of belgium', 'konigreich belgien', 'koninkrijk belgie', 'reino de belgica', 'royaume de belgique']::text[], 'Europa', 'Europa occidental', true, 4.6284, 50.6612),
  ('BF', 'BFA', '854', 'Burkina Faso', 'burkina faso', '{}', 'África', 'África occidental', true, -1.6094, 12.6398),
  ('BG', 'BGR', '100', 'Bulgaria', 'bulgaria', array['republic of bulgaria', 'republica de bulgaria']::text[], 'Europa', 'Europa oriental', true, 25.234, 42.6563),
  ('BH', 'BHR', '048', 'Baréin', 'barein', array['bahrain', 'bahrein', 'kingdom of bahrain', 'mamlakat al bahrayn', 'reino de bahrein']::text[], 'Asia', 'Asia occidental', false, 50.55, 26),
  ('BI', 'BDI', '108', 'Burundi', 'burundi', array['republic of burundi', 'republica de burundi', 'republika yuburundi', 'republique du burundi']::text[], 'África', 'África oriental', true, 29.9143, -3.3739),
  ('BJ', 'BEN', '204', 'Benín', 'benin', array['republic of benin', 'republica de benin', 'republique du benin']::text[], 'África', 'África occidental', true, 2.4513, 10.4028),
  ('BL', 'BLM', '652', 'San Bartolomé', 'san bartolome', array['colectividad de san barthelemy', 'collectivite de saint barthelemy', 'collectivity of saint barthelemy', 'saint barthelemy', 'st barthelemy']::text[], 'América', 'Caribe', false, -63.4167, 18.5),
  ('BM', 'BMU', '060', 'Bermudas', 'bermudas', array['bermuda', 'somers isles', 'the bermudas', 'the islands of bermuda']::text[], 'América', 'América del Norte', false, -64.75, 32.3333),
  ('BN', 'BRN', '096', 'Brunéi', 'brunei', array['brunei darussalam', 'nacion de brunei morada de la paz', 'nation of brunei', 'nation of brunei abode of peace', 'negara brunei darussalam', 'the abode of peace']::text[], 'Asia', 'Sudeste asiático', true, 115.0161, 4.7446),
  ('BO', 'BOL', '068', 'Bolivia', 'bolivia', array['bolivia plurinational state of', 'buliwya', 'buliwya mamallaqta', 'estado plurinacional de bolivia', 'plurinational state of bolivia', 'teta volivia', 'wuliwya', 'wuliwya suyu']::text[], 'América', 'América del Sur', true, -64.6494, -16.7264),
  ('BQ', 'BES', '535', 'Caribe neerlandés', 'caribe neerlandes', array['bes islands', 'bonaire san eustaquio y saba', 'bonaire sint eustatius and saba', 'caribbean netherlands']::text[], 'América', 'Caribe', false, -68.25, 12.18),
  ('BR', 'BRA', '076', 'Brasil', 'brasil', array['brazil', 'federative republic of brazil', 'republica federativa del brasil', 'republica federativa do brasil']::text[], 'América', 'América del Sur', true, -51.56, -9.9298),
  ('BS', 'BHS', '044', 'Bahamas', 'bahamas', array['commonwealth de las bahamas', 'commonwealth of the bahamas', 'the bahamas']::text[], 'América', 'Caribe', true, -77.9997, 24.7633),
  ('BT', 'BTN', '064', 'Bután', 'butan', array['bhutan', 'kingdom of bhutan', 'reino de butan']::text[], 'Asia', 'Asia meridional', true, 90.5007, 27.5176),
  ('BV', 'BVT', '074', 'Isla Bouvet', 'isla bouvet', array['bouvet island']::text[], 'América', 'América del Sur', false, 3.4, -54.4333),
  ('BW', 'BWA', '072', 'Botsuana', 'botsuana', array['botswana', 'lefatshe la botswana', 'republic of botswana', 'republica de botswana']::text[], 'África', 'África austral', true, 23.8256, -22.0775),
  ('BY', 'BLR', '112', 'Bielorrusia', 'bielorrusia', array['belarus', 'bielarus', 'republic of belarus', 'republica de belarus']::text[], 'Europa', 'Europa oriental', true, 27.9554, 53.6338),
  ('BZ', 'BLZ', '084', 'Belice', 'belice', array['belize']::text[], 'América', 'Centroamérica', true, -88.7078, 17.186),
  ('CA', 'CAN', '124', 'Canadá', 'canada', '{}', 'América', 'América del Norte', true, -103.756, 58.2142),
  ('CC', 'CCK', '166', 'Islas Cocos', 'islas cocos', array['cocos islands', 'cocos keeling islands', 'islas cocos o islas keeling', 'keeling islands', 'territorio de los keeling islas cocos', 'territory of the cocos keeling islands']::text[], 'Oceanía', 'Australia y Nueva Zelanda', false, 96.8333, -12.5),
  ('CD', 'COD', '180', 'República Democrática del Congo', 'republica democratica del congo', array['congo democratic republic of the', 'congo kinshasa', 'congo rep dem', 'congo the democratic republic of the', 'dem rep congo', 'democratic republic of congo', 'democratic republic of the congo', 'dr congo', 'drc', 'rd congo', 'rdc']::text[], 'África', 'África central', true, 23.7849, -2.4888),
  ('CF', 'CAF', '140', 'República Centroafricana', 'republica centroafricana', array['central african rep', 'central african republic', 'republique centrafricaine']::text[], 'África', 'África central', true, 20.9389, 6.8687),
  ('CG', 'COG', '178', 'República del Congo', 'republica del congo', array['congo', 'congo brazzaville', 'republic of the congo']::text[], 'África', 'África central', true, 15.7921, -0.2183),
  ('CH', 'CHE', '756', 'Suiza', 'suiza', array['confederacion suiza', 'schweiz', 'suisse', 'svizra', 'svizzera', 'swiss confederation', 'switzerland']::text[], 'Europa', 'Europa occidental', true, 8.1239, 46.8406),
  ('CI', 'CIV', '384', 'Costa de Marfil', 'costa de marfil', array['cote divoire', 'ivory coast', 'republic of cote divoire', 'republic of ivory coast', 'republica de cote divoire', 'republique de cote divoire']::text[], 'África', 'África occidental', true, -5.6206, 7.5433),
  ('CK', 'COK', '184', 'Islas Cook', 'islas cook', array['cook islands', 'kuki airani']::text[], 'Oceanía', 'Polinesia', false, -159.7667, -21.2333),
  ('CL', 'CHL', '152', 'Chile', 'chile', array['republic of chile', 'republica de chile']::text[], 'América', 'América del Sur', true, -72.939, -45.7126),
  ('CM', 'CMR', '120', 'Camerún', 'camerun', array['cameroon', 'republic of cameroon', 'republica de camerun', 'republique du cameroun']::text[], 'África', 'África central', true, 12.3925, 4.9617),
  ('CN', 'CHN', '156', 'China', 'china', array['peoples republic of china', 'republica popular china', 'republica popular de china', 'zhongguo', 'zhonghua', 'zhonghua renmin gongheguo']::text[], 'Asia', 'Asia oriental', true, 106.1183, 32.6468),
  ('CO', 'COL', '170', 'Colombia', 'colombia', array['republic of colombia', 'republica de colombia']::text[], 'América', 'América del Sur', true, -73.1927, 3.7427),
  ('CR', 'CRI', '188', 'Costa Rica', 'costa rica', array['republic of costa rica', 'republica de costa rica']::text[], 'América', 'Centroamérica', true, -84.1115, 10.0854),
  ('CU', 'CUB', '192', 'Cuba', 'cuba', array['republic of cuba', 'republica de cuba']::text[], 'América', 'Caribe', true, -77.993, 21.5499),
  ('CV', 'CPV', '132', 'Cabo Verde', 'cabo verde', array['cape verde', 'republic of cabo verde', 'republica de cabo verde']::text[], 'África', 'África occidental', false, -24, 16),
  ('CW', 'CUW', '531', 'Curazao', 'curazao', array['country of curacao', 'curacao', 'korsou', 'land curacao', 'pais de curazao', 'pais korsou']::text[], 'América', 'Caribe', false, -68.9333, 12.1167),
  ('CX', 'CXR', '162', 'Isla de Navidad', 'isla de navidad', array['christmas island', 'territorio de la isla de navidad', 'territory of christmas island']::text[], 'Oceanía', 'Australia y Nueva Zelanda', false, 105.6667, -10.5),
  ('CY', 'CYP', '196', 'Chipre', 'chipre', array['cyprus', 'kypros', 'n cyprus', 'northern cyprus', 'republic of cyprus', 'republica de chipre', 'republica turca del norte de chipre', 'turkish republic of northern cyprus']::text[], 'Asia', 'Asia occidental', true, 33.3082, 35.0164),
  ('CZ', 'CZE', '203', 'Chequia', 'chequia', array['ceska republika', 'cesko', 'czech republic', 'czechia', 'republica checa']::text[], 'Europa', 'Europa oriental', true, 14.8814, 49.9795),
  ('DE', 'DEU', '276', 'Alemania', 'alemania', array['bundesrepublik deutschland', 'deutschland', 'federal republic of germany', 'germany', 'republica federal de alemania']::text[], 'Europa', 'Europa occidental', true, 9.9562, 51.3063),
  ('DJ', 'DJI', '262', 'Yibuti', 'yibuti', array['djibouti', 'gabuuti', 'gabuutih ummuuno', 'jabuuti', 'jamhuuriyadda jabuuti', 'republic of djibouti', 'republica de djibouti', 'republique de djibouti']::text[], 'África', 'África oriental', true, 42.5289, 11.7698),
  ('DK', 'DNK', '208', 'Dinamarca', 'dinamarca', array['danmark', 'denmark', 'kingdom of denmark', 'kongeriget danmark', 'reino de dinamarca']::text[], 'Europa', 'Europa septentrional', true, 9.1097, 56.1342),
  ('DM', 'DMA', '212', 'Dominica', 'dominica', array['commonwealth of dominica', 'dominique', 'mancomunidad de dominica', 'waitu kubuli']::text[], 'América', 'Caribe', false, -61.3333, 15.4167),
  ('DO', 'DOM', '214', 'República Dominicana', 'republica dominicana', array['dominican rep', 'dominican republic']::text[], 'América', 'Caribe', true, -70.5522, 18.9317),
  ('DZ', 'DZA', '012', 'Argelia', 'argelia', array['algeria', 'algerie', 'dzayer', 'peoples democratic republic of algeria', 'republica argelina democratica y popular']::text[], 'África', 'África septentrional', true, 2.6877, 28.0677),
  ('EC', 'ECU', '218', 'Ecuador', 'ecuador', array['republic of ecuador', 'republica del ecuador']::text[], 'América', 'América del Sur', true, -78.4289, -1.3743),
  ('EE', 'EST', '233', 'Estonia', 'estonia', array['eesti', 'eesti vabariik', 'republic of estonia', 'republica de estonia']::text[], 'Europa', 'Europa septentrional', true, 25.8372, 58.6833),
  ('EG', 'EGY', '818', 'Egipto', 'egipto', array['arab republic of egypt', 'egypt', 'republica arabe de egipto']::text[], 'África', 'África septentrional', true, 29.6901, 26.4602),
  ('EH', 'ESH', '732', 'Sáhara Occidental', 'sahara occidental', array['republica arabe saharaui democratica', 'sahrawi arab democratic republic', 'tanezroft tutrimt', 'w sahara', 'western sahara']::text[], 'África', 'África septentrional', true, -12.5262, 24.0144),
  ('ER', 'ERI', '232', 'Eritrea', 'eritrea', array['dawlat iritriya', 'estado de eritrea', 'iritriya', 'state of eritrea']::text[], 'África', 'África oriental', true, 38.0886, 16.0391),
  ('ES', 'ESP', '724', 'España', 'espana', array['kingdom of spain', 'reino de espana', 'spain']::text[], 'Europa', 'Europa meridional', true, -3.6161, 40.3499),
  ('ET', 'ETH', '231', 'Etiopía', 'etiopia', array['ethiopia', 'federal democratic republic of ethiopia', 'republica democratica federal de etiopia']::text[], 'África', 'África oriental', true, 39.2273, 8.278),
  ('FI', 'FIN', '246', 'Finlandia', 'finlandia', array['finland', 'republic of finland', 'republica de finlandia', 'republiken finland', 'suomen tasavalta', 'suomi']::text[], 'Europa', 'Europa septentrional', true, 27.3441, 63.6571),
  ('FJ', 'FJI', '242', 'Fiyi', 'fiyi', array['fiji', 'fiji ganarajya', 'matanitu ko viti', 'republic of fiji', 'republica de fiji', 'viti']::text[], 'Oceanía', 'Melanesia', true, 179.3461, -16.5585),
  ('FK', 'FLK', '238', 'Islas Malvinas', 'islas malvinas', array['falkland is', 'falkland islands', 'falkland islands malvinas', 'malvinas']::text[], 'América', 'América del Sur', true, -58.7456, -51.6747),
  ('FM', 'FSM', '583', 'Micronesia', 'micronesia', array['estados federados de micronesia', 'federated states of micronesia', 'micronesia federated states of']::text[], 'Oceanía', 'Micronesia', false, 158.25, 6.9167),
  ('FO', 'FRO', '234', 'Islas Feroe', 'islas feroe', array['faeroe islands', 'faroe islands', 'islas faroe']::text[], 'Europa', 'Europa septentrional', false, -7, 62),
  ('FR', 'FRA', '250', 'Francia', 'francia', array['france', 'french republic', 'republica frances', 'republique francaise']::text[], 'Europa', 'Europa occidental', true, 2.3521, 46.6132),
  ('GA', 'GAB', '266', 'Gabón', 'gabon', array['gabonese republic', 'republica de gabon', 'republique gabonaise']::text[], 'África', 'África central', true, 11.6953, -0.6655),
  ('GB', 'GBR', '826', 'Reino Unido', 'reino unido', array['england', 'escocia', 'gales', 'gran bretana', 'great britain', 'inglaterra', 'irlanda del norte', 'reino unido de gran bretana e irlanda del norte', 'scotland', 'uk', 'united kingdom', 'united kingdom of great britain and northern ireland', 'wales']::text[], 'Europa', 'Europa septentrional', true, -1.4972, 52.9336),
  ('GD', 'GRD', '308', 'Granada', 'granada', array['grenada']::text[], 'América', 'Caribe', false, -61.6667, 12.1167),
  ('GE', 'GEO', '268', 'Georgia', 'georgia', array['sakartvelo']::text[], 'Asia', 'Asia occidental', true, 43.5608, 42.0384),
  ('GF', 'GUF', '254', 'Guayana Francesa', 'guayana francesa', array['french guiana', 'guyane']::text[], 'América', 'América del Sur', true, -53.0663, 3.9346),
  ('GG', 'GGY', '831', 'Guernesey', 'guernesey', array['bailia de guernsey', 'bailiwick of guernsey', 'bailliage de guernesey', 'guernsey']::text[], 'Europa', 'Europa septentrional', false, -2.5833, 49.4667),
  ('GH', 'GHA', '288', 'Ghana', 'ghana', array['republic of ghana', 'republica de ghana']::text[], 'África', 'África occidental', true, -0.9874, 8.0309),
  ('GI', 'GIB', '292', 'Gibraltar', 'gibraltar', '{}', 'Europa', 'Europa meridional', false, -5.35, 36.1333),
  ('GL', 'GRL', '304', 'Groenlandia', 'groenlandia', array['greenland']::text[], 'América', 'América del Norte', true, -41.438, 74.7926),
  ('GM', 'GMB', '270', 'Gambia', 'gambia', array['republic of the gambia', 'republica de gambia', 'the gambia']::text[], 'África', 'África occidental', true, -16.2662, 13.3812),
  ('GN', 'GIN', '324', 'Guinea', 'guinea', array['republic of guinea', 'republica de guinea', 'republique de guinee']::text[], 'África', 'África occidental', true, -10.0059, 10.6104),
  ('GP', 'GLP', '312', 'Guadalupe', 'guadalupe', array['guadeloupe', 'gwadloup']::text[], 'América', 'Caribe', false, -61.5833, 16.25),
  ('GQ', 'GNQ', '226', 'Guinea Ecuatorial', 'guinea ecuatorial', array['eq guinea', 'equatorial guinea', 'republic of equatorial guinea', 'republica da guine equatorial', 'republica de guinea ecuatorial', 'republique de guinee equatoriale']::text[], 'África', 'África central', true, 10.3629, 1.6342),
  ('GR', 'GRC', '300', 'Grecia', 'grecia', array['ellada', 'greece', 'hellenic republic', 'republica helenica']::text[], 'Europa', 'Europa meridional', true, 21.8108, 39.2288),
  ('GS', 'SGS', '239', 'Islas Georgia del Sur y Sándwich del Sur', 'islas georgia del sur y sandwich del sur', array['georgia del sur y las islas sandwich del sur', 'islas georgias del sur y sandwich del sur', 'south georgia', 'south georgia and the south sandwich islands']::text[], 'América', 'América del Sur', false, -37, -54.5),
  ('GT', 'GTM', '320', 'Guatemala', 'guatemala', array['republic of guatemala', 'republica de guatemala']::text[], 'América', 'Centroamérica', true, -90.2152, 15.0868),
  ('GU', 'GUM', '316', 'Guam', 'guam', array['guahan']::text[], 'Oceanía', 'Micronesia', false, 144.7833, 13.4667),
  ('GW', 'GNB', '624', 'Guinea-Bisáu', 'guinea bisau', array['guinea bissau', 'republic of guinea bissau', 'republica da guine bissau', 'republica de guinea bissau']::text[], 'África', 'África occidental', true, -15.1337, 11.9826),
  ('GY', 'GUY', '328', 'Guyana', 'guyana', array['co operative republic of guyana', 'republica cooperativa de guyana']::text[], 'América', 'América del Sur', true, -58.9886, 5.4344),
  ('HK', 'HKG', '344', 'Hong Kong', 'hong kong', array['hong kong region administrativa especial de la republica popular china', 'hong kong special administrative region of the peoples republic of china', 'rae de hong kong china']::text[], 'Asia', 'Asia oriental', false, 114.188, 22.267),
  ('HM', 'HMD', '334', 'Islas Heard y McDonald', 'islas heard y mcdonald', array['heard island and mcdonald islands']::text[], 'Oceanía', 'Australia y Nueva Zelanda', false, 72.5167, -53.1),
  ('HN', 'HND', '340', 'Honduras', 'honduras', array['republic of honduras', 'republica de honduras']::text[], 'América', 'Centroamérica', true, -86.6139, 14.8102),
  ('HR', 'HRV', '191', 'Croacia', 'croacia', array['croatia', 'hrvatska', 'republic of croatia', 'republica de croacia', 'republika hrvatska']::text[], 'Europa', 'Europa meridional', true, 16.514, 45.8276),
  ('HT', 'HTI', '332', 'Haití', 'haiti', array['repiblik ayiti', 'republic of haiti', 'republica de haiti', 'republique dhaiti']::text[], 'América', 'Caribe', true, -72.258, 18.8785),
  ('HU', 'HUN', '348', 'Hungría', 'hungria', array['hungary', 'republic of hungary']::text[], 'Europa', 'Europa oriental', true, 19.3484, 47.1837),
  ('ID', 'IDN', '360', 'Indonesia', 'indonesia', array['republic of indonesia', 'republica de indonesia', 'republik indonesia']::text[], 'Asia', 'Sudeste asiático', true, 101.6377, -0.3797),
  ('IE', 'IRL', '372', 'Irlanda', 'irlanda', array['eire', 'ireland', 'poblacht na heireann', 'republic of ireland', 'republica de irlanda']::text[], 'Europa', 'Europa septentrional', true, -8.032, 53.1578),
  ('IL', 'ISR', '376', 'Israel', 'israel', array['estado de israel', 'medinat yisrael', 'state of israel']::text[], 'Asia', 'Asia occidental', true, 34.8773, 30.8989),
  ('IM', 'IMN', '833', 'Isla de Man', 'isla de man', array['ellan vannin', 'isle of man', 'mann', 'mannin']::text[], 'Europa', 'Europa septentrional', false, -4.5, 54.25),
  ('IN', 'IND', '356', 'India', 'india', array['bharat', 'bharat ganrajya', 'republic of india', 'republica de la india']::text[], 'Asia', 'Asia meridional', true, 79.5208, 22.8258),
  ('IO', 'IOT', '086', 'Territorio Británico del Océano Índico', 'territorio britanico del oceano indico', array['british indian ocean territory']::text[], 'África', 'África oriental', false, 71.5, -6),
  ('IQ', 'IRQ', '368', 'Irak', 'irak', array['iraq', 'jumhuriyyat al iraq', 'republic of iraq', 'republica de irak']::text[], 'Asia', 'Asia occidental', true, 43.537, 32.908),
  ('IR', 'IRN', '364', 'Irán', 'iran', array['iran islamic republic of', 'islamic republic of iran', 'jomhuri ye eslami ye iran', 'persia', 'republica islamica de iran']::text[], 'Asia', 'Asia meridional', true, 54.2569, 32.3769),
  ('IS', 'ISL', '352', 'Islandia', 'islandia', array['iceland', 'island', 'republic of iceland']::text[], 'Europa', 'Europa septentrional', true, -18.79, 64.9802),
  ('IT', 'ITA', '380', 'Italia', 'italia', array['italian republic', 'italy', 'repubblica italiana', 'republica italiana']::text[], 'Europa', 'Europa meridional', true, 10.9833, 44.9597),
  ('JE', 'JEY', '832', 'Jersey', 'jersey', array['bailia de jersey', 'bailiwick of jersey', 'bailliage de jerri', 'bailliage de jersey']::text[], 'Europa', 'Europa septentrional', false, -2.1667, 49.25),
  ('JM', 'JAM', '388', 'Jamaica', 'jamaica', '{}', 'América', 'Caribe', true, -77.3483, 18.1274),
  ('JO', 'JOR', '400', 'Jordania', 'jordania', array['al mamlakah al urduniyah al hashimiyah', 'hashemite kingdom of jordan', 'jordan', 'reino hachemita de jordania']::text[], 'Asia', 'Asia occidental', true, 36.3455, 30.9167),
  ('JP', 'JPN', '392', 'Japón', 'japon', array['japan', 'nihon', 'nippon']::text[], 'Asia', 'Asia oriental', true, 138.4275, 35.9537),
  ('KE', 'KEN', '404', 'Kenia', 'kenia', array['jamhuri ya kenya', 'kenya', 'republic of kenya', 'republica de kenya']::text[], 'África', 'África oriental', true, 37.7977, 0.5891),
  ('KG', 'KGZ', '417', 'Kirguistán', 'kirguistan', array['kirguizistan', 'kyrgyz republic', 'kyrgyz respublikasy', 'kyrgyzstan', 'republica kirguisa']::text[], 'Asia', 'Asia central', true, 74.6042, 41.5577),
  ('KH', 'KHM', '116', 'Camboya', 'camboya', array['cambodia', 'kingdom of cambodia', 'reino de camboya']::text[], 'Asia', 'Sudeste asiático', true, 104.719, 12.7291),
  ('KI', 'KIR', '296', 'Kiribati', 'kiribati', array['independent and sovereign republic of kiribati', 'republic of kiribati', 'republica independiente y soberano de kiribati', 'ribaberiki kiribati']::text[], 'Oceanía', 'Micronesia', false, 173, 1.4167),
  ('KM', 'COM', '174', 'Comoras', 'comoras', array['al ittihad al qumuri', 'comoros', 'udzima wa komori', 'union de las comoras', 'union des comores', 'union of the comoros']::text[], 'África', 'África oriental', false, 44.25, -12.1667),
  ('KN', 'KNA', '659', 'San Cristóbal y Nieves', 'san cristobal y nieves', array['federacion de san cristobal y nevis', 'federation of saint christopher and nevis', 'saint kitts and nevis']::text[], 'América', 'Caribe', false, -62.75, 17.3333),
  ('KP', 'PRK', '408', 'Corea del Norte', 'corea del norte', array['choson minjujuui inmin konghwaguk', 'dem rep korea', 'democratic peoples republic of korea', 'dprk', 'korea democratic peoples republic of', 'north korea', 'republica popular democratica de corea']::text[], 'Asia', 'Asia oriental', true, 126.5781, 40.1481),
  ('KR', 'KOR', '410', 'Corea del Sur', 'corea del sur', array['corea', 'korea republic of', 'republic of korea', 'republica de corea', 'south korea']::text[], 'Asia', 'Asia oriental', true, 127.9702, 36.3568),
  ('KW', 'KWT', '414', 'Kuwait', 'kuwait', array['dawlat al kuwait', 'estado de kuwait', 'state of kuwait']::text[], 'Asia', 'Asia occidental', true, 47.6566, 29.4243),
  ('KY', 'CYM', '136', 'Islas Caimán', 'islas caiman', array['cayman islands']::text[], 'América', 'Caribe', false, -80.5, 19.5),
  ('KZ', 'KAZ', '398', 'Kazajistán', 'kazajistan', array['kazakhstan', 'qazaqstan', 'republic of kazakhstan', 'republica de kazajstan', 'respublika kazakhstan']::text[], 'Asia', 'Asia central', true, 67.4523, 48.606),
  ('LA', 'LAO', '418', 'Laos', 'laos', array['lao', 'lao pdr', 'lao peoples democratic republic', 'republica democratica popular lao', 'sathalanalat paxathipatai paxaxon lao']::text[], 'Asia', 'Sudeste asiático', true, 102.7128, 19.4093),
  ('LB', 'LBN', '422', 'Líbano', 'libano', array['al jumhuriyah al libnaniyah', 'lebanese republic', 'lebanon', 'republica libanesa']::text[], 'Asia', 'Asia occidental', true, 36.0055, 34.1077),
  ('LC', 'LCA', '662', 'Santa Lucía', 'santa lucia', array['saint lucia']::text[], 'América', 'Caribe', false, -60.9667, 13.8833),
  ('LI', 'LIE', '438', 'Liechtenstein', 'liechtenstein', array['furstentum liechtenstein', 'principado de liechtenstein', 'principality of liechtenstein']::text[], 'Europa', 'Europa occidental', false, 9.5333, 47.2667),
  ('LK', 'LKA', '144', 'Sri Lanka', 'sri lanka', array['democratic socialist republic of sri lanka', 'ilankai', 'republica democratica socialista de sri lanka']::text[], 'Asia', 'Asia meridional', true, 80.6672, 7.7005),
  ('LR', 'LBR', '430', 'Liberia', 'liberia', array['republic of liberia', 'republica de liberia']::text[], 'África', 'África occidental', true, -9.4841, 6.4487),
  ('LS', 'LSO', '426', 'Lesoto', 'lesoto', array['kingdom of lesotho', 'lesotho', 'muso oa lesotho', 'reino de lesotho']::text[], 'África', 'África austral', true, 28.1808, -29.6397),
  ('LT', 'LTU', '440', 'Lituania', 'lituania', array['lietuvos respublika', 'lithuania', 'republic of lithuania', 'republica de lituania']::text[], 'Europa', 'Europa septentrional', true, 23.8707, 55.2526),
  ('LU', 'LUX', '442', 'Luxemburgo', 'luxemburgo', array['gran ducado de luxemburgo', 'grand duche de luxembourg', 'grand duchy of luxembourg', 'groussherzogtum letzebuerg', 'luxembourg']::text[], 'Europa', 'Europa occidental', true, 5.9678, 49.7071),
  ('LV', 'LVA', '428', 'Letonia', 'letonia', array['latvia', 'latvijas republika', 'republic of latvia', 'republica de letonia']::text[], 'Europa', 'Europa septentrional', true, 25.3082, 57.0534),
  ('LY', 'LBY', '434', 'Libia', 'libia', array['dawlat libya', 'estado de libia', 'libya', 'state of libya']::text[], 'África', 'África septentrional', true, 19.1764, 26.2504)
on conflict (iso2) do update set
  iso3 = excluded.iso3,
  numerico = excluded.numerico,
  nombre = excluded.nombre,
  nombre_normalizado = excluded.nombre_normalizado,
  alias = excluded.alias,
  continente = excluded.continente,
  subregion = excluded.subregion,
  con_geometria = excluded.con_geometria,
  lon = excluded.lon,
  lat = excluded.lat;

do $$ begin
  assert (select count(*) from public.paises) = 136, 'paises A–L: conteo inesperado';
end $$;
