-- Migración 2 (parte) · geo_semilla_paises_2 — países M–Z de supabase/seed/geo.sql
-- (pnpm geo:build), filas sin cambios; separado de `geo` por tamaño.

insert into public.paises (iso2, iso3, numerico, nombre, nombre_normalizado, alias, continente, subregion, con_geometria, lon, lat) values
  ('MA', 'MAR', '504', 'Marruecos', 'marruecos', array['al mamlakah al magribiyah', 'kingdom of morocco', 'morocco', 'reino de marruecos']::text[], 'África', 'África septentrional', true, -7.6528, 31.4222),
  ('MC', 'MCO', '492', 'Mónaco', 'monaco', array['principado de monaco', 'principality of monaco', 'principaute de monaco']::text[], 'Europa', 'Europa occidental', false, 7.4, 43.7333),
  ('MD', 'MDA', '498', 'Moldavia', 'moldavia', array['moldova', 'moldova republic of', 'republic of moldova', 'republica de moldova', 'republica moldova']::text[], 'Europa', 'Europa oriental', true, 28.4994, 47.3243),
  ('ME', 'MNE', '499', 'Montenegro', 'montenegro', array['crna gora']::text[], 'Europa', 'Europa meridional', true, 19.2638, 42.7695),
  ('MF', 'MAF', '663', 'San Martín', 'san martin', array['collectivite de saint martin', 'collectivity of saint martin', 'saint martin', 'saint martin french part']::text[], 'América', 'Caribe', false, -63.95, 18.0833),
  ('MG', 'MDG', '450', 'Madagascar', 'madagascar', array['repoblikani madagasikara', 'republic of madagascar', 'republica de madagascar', 'republique de madagascar']::text[], 'África', 'África oriental', true, 46.673, -19.0485),
  ('MH', 'MHL', '584', 'Islas Marshall', 'islas marshall', array['aolepan aorokin majel', 'marshall islands', 'republic of the marshall islands', 'republica de las islas marshall']::text[], 'Oceanía', 'Micronesia', false, 168, 9),
  ('MK', 'MKD', '807', 'Macedonia del Norte', 'macedonia del norte', array['macedonia', 'macedonia the former yugoslav republic of', 'north macedonia', 'republic of north macedonia', 'republica de macedonia del norte', 'the former yugoslav republic of macedonia']::text[], 'Europa', 'Europa meridional', true, 21.7276, 41.6079),
  ('ML', 'MLI', '466', 'Mali', 'mali', array['republic of mali', 'republica de mali', 'republique du mali']::text[], 'África', 'África occidental', true, -2.2644, 18.0653),
  ('MM', 'MMR', '104', 'Myanmar', 'myanmar', array['birmania', 'burma', 'myanmar birmania', 'pyidaunzu thanmada myama nainngandaw', 'republic of the union of myanmar', 'republica de la union de myanmar']::text[], 'Asia', 'Sudeste asiático', true, 96.1543, 21.2641),
  ('MN', 'MNG', '496', 'Mongolia', 'mongolia', '{}', 'Asia', 'Asia oriental', true, 102.8708, 46.4315),
  ('MO', 'MAC', '446', 'Macao', 'macao', array['macao region administrativa especial de la republica popular china', 'macao special administrative region of the peoples republic of china', 'macau', 'rae de macao china', 'regiao administrativa especial de macau da republica popular da china']::text[], 'Asia', 'Asia oriental', false, 113.55, 22.1667),
  ('MP', 'MNP', '580', 'Islas Marianas del Norte', 'islas marianas del norte', array['commonwealth of the northern mariana islands', 'mancomunidad de las islas marianas del norte', 'northern mariana islands', 'sankattan siha na islas marianas']::text[], 'Oceanía', 'Micronesia', false, 145.75, 15.2),
  ('MQ', 'MTQ', '474', 'Martinica', 'martinica', array['martinique']::text[], 'América', 'Caribe', false, -61, 14.6667),
  ('MR', 'MRT', '478', 'Mauritania', 'mauritania', array['islamic republic of mauritania', 'republica islamica de mauritania']::text[], 'África', 'África occidental', true, -9.7579, 19.9955),
  ('MS', 'MSR', '500', 'Montserrat', 'montserrat', '{}', 'América', 'Caribe', false, -62.2, 16.75),
  ('MT', 'MLT', '470', 'Malta', 'malta', array['repubblika ta malta', 'republic of malta', 'republica de malta']::text[], 'Europa', 'Europa meridional', false, 14.5833, 35.8333),
  ('MU', 'MUS', '480', 'Mauricio', 'mauricio', array['mauritius', 'republic of mauritius', 'republica de mauricio', 'republique de maurice']::text[], 'África', 'África oriental', false, 57.55, -20.2833),
  ('MV', 'MDV', '462', 'Maldivas', 'maldivas', array['dhivehi raajjeyge jumhooriyya', 'maldive islands', 'maldives', 'republic of the maldives', 'republica de las maldivas']::text[], 'Asia', 'Asia meridional', false, 73, 3.25),
  ('MW', 'MWI', '454', 'Malaui', 'malaui', array['malawi', 'republic of malawi', 'republica de malawi']::text[], 'África', 'África oriental', true, 33.7532, -13.2858),
  ('MX', 'MEX', '484', 'México', 'mexico', array['estados unidos mexicanos', 'mexicanos', 'united mexican states']::text[], 'América', 'Centroamérica', true, -102.5339, 23.9403),
  ('MY', 'MYS', '458', 'Malasia', 'malasia', array['malaysia']::text[], 'Asia', 'Sudeste asiático', true, 114.1112, 2.8978),
  ('MZ', 'MOZ', '508', 'Mozambique', 'mozambique', array['republic of mozambique', 'republica de mocambique', 'republica de mozambique']::text[], 'África', 'África oriental', true, 37.9557, -14.9126),
  ('NA', 'NAM', '516', 'Namibia', 'namibia', array['namibie', 'republic of namibia', 'republica de namibia']::text[], 'África', 'África austral', true, 17.0404, -21.442),
  ('NC', 'NCL', '540', 'Nueva Caledonia', 'nueva caledonia', array['new caledonia']::text[], 'Oceanía', 'Melanesia', true, 165.5936, -21.3104),
  ('NE', 'NER', '562', 'Níger', 'niger', array['nijar', 'republic of niger', 'republica de niger']::text[], 'África', 'África occidental', true, 9.3348, 17.3435),
  ('NF', 'NFK', '574', 'Isla Norfolk', 'isla norfolk', array['isla de norfolk', 'norfolk island', 'teratri of norfk ailen', 'territorio de la isla norfolk', 'territory of norfolk island']::text[], 'Oceanía', 'Australia y Nueva Zelanda', false, 167.95, -29.0333),
  ('NG', 'NGA', '566', 'Nigeria', 'nigeria', array['federal republic of nigeria', 'naijiria', 'nijeriya', 'republica federal de nigeria']::text[], 'África', 'África occidental', true, 7.9909, 9.5442),
  ('NI', 'NIC', '558', 'Nicaragua', 'nicaragua', array['republic of nicaragua', 'republica de nicaragua']::text[], 'América', 'Centroamérica', true, -84.9513, 12.8003),
  ('NL', 'NLD', '528', 'Países Bajos', 'paises bajos', array['holanda', 'holland', 'kingdom of the netherlands', 'nederland', 'netherlands', 'netherlands kingdom of the', 'the netherlands']::text[], 'Europa', 'Europa occidental', true, 5.458, 52.4263),
  ('NO', 'NOR', '578', 'Noruega', 'noruega', array['kingdom of norway', 'kongeriket noreg', 'kongeriket norge', 'noreg', 'norge', 'norway', 'reino de noruega']::text[], 'Europa', 'Europa septentrional', true, 7.5927, 60.6318),
  ('NP', 'NPL', '524', 'Nepal', 'nepal', array['federal democratic republic of nepal', 'loktantrik ganatantra nepal', 'republica democratica federal de nepal']::text[], 'Asia', 'Asia meridional', true, 83.4103, 28.3593),
  ('NR', 'NRU', '520', 'Nauru', 'nauru', array['naoero', 'pleasant island', 'republic of nauru', 'republica de nauru', 'ripublik naoero']::text[], 'Oceanía', 'Micronesia', false, 166.9167, -0.5333),
  ('NU', 'NIU', '570', 'Niue', 'niue', '{}', 'Oceanía', 'Polinesia', false, -169.8667, -19.0333),
  ('NZ', 'NZL', '554', 'Nueva Zelanda', 'nueva zelanda', array['aotearoa', 'new zealand', 'nueva zelandia']::text[], 'Oceanía', 'Australia y Nueva Zelanda', true, 169.8044, -44.8071),
  ('OM', 'OMN', '512', 'Omán', 'oman', array['sultanate of oman', 'sultanato de oman']::text[], 'Asia', 'Asia occidental', true, 57.2201, 21.814),
  ('PA', 'PAN', '591', 'Panamá', 'panama', array['republic of panama', 'republica de panama']::text[], 'América', 'Centroamérica', true, -80.9593, 8.3211),
  ('PE', 'PER', '604', 'Perú', 'peru', array['republic of peru', 'republica de peru', 'republica del peru']::text[], 'América', 'América del Sur', true, -76.6992, -6.8627),
  ('PF', 'PYF', '258', 'Polinesia Francesa', 'polinesia francesa', array['french polynesia', 'polinesia frances', 'polynesie francaise', 'porinetia farani']::text[], 'Oceanía', 'Polinesia', false, -140, -15),
  ('PG', 'PNG', '598', 'Papúa Nueva Guinea', 'papua nueva guinea', array['estado independiente de papua nueva guinea', 'independen stet bilong papua niugini', 'independent state of papua new guinea', 'papua new guinea']::text[], 'Oceanía', 'Melanesia', true, 143.776, -5.8414),
  ('PH', 'PHL', '608', 'Filipinas', 'filipinas', array['philippines', 'republic of the philippines', 'republica de las filipinas', 'republika ng pilipinas']::text[], 'Asia', 'Sudeste asiático', true, 121.2883, 16.7988),
  ('PK', 'PAK', '586', 'Pakistán', 'pakistan', array['islami jumhuriyaeh pakistan', 'islamic republic of pakistan', 'republica islamica de pakistan']::text[], 'Asia', 'Asia meridional', true, 69.066, 29.4765),
  ('PL', 'POL', '616', 'Polonia', 'polonia', array['poland', 'republic of poland', 'republica de polonia', 'rzeczpospolita polska']::text[], 'Europa', 'Europa oriental', true, 19.311, 52.1589),
  ('PM', 'SPM', '666', 'San Pedro y Miquelón', 'san pedro y miquelon', array['collectivite territoriale de saint pierre et miquelon', 'saint pierre and miquelon']::text[], 'América', 'América del Norte', false, -56.3333, 46.8333),
  ('PN', 'PCN', '612', 'Islas Pitcairn', 'islas pitcairn', array['grupo de islas pitcairn', 'pitcairn', 'pitcairn group of islands', 'pitcairn henderson ducie and oeno islands', 'pitcairn islands']::text[], 'Oceanía', 'Polinesia', false, -130.1, -25.0667),
  ('PR', 'PRI', '630', 'Puerto Rico', 'puerto rico', array['asociado de puerto rico', 'commonwealth of puerto rico', 'estado libre asociado de puerto rico']::text[], 'América', 'Caribe', true, -66.6012, 18.2167),
  ('PS', 'PSE', '275', 'Palestina', 'palestina', array['dawlat filastin', 'estado de palestina', 'palestine', 'palestine state of', 'state of palestine', 'territorios palestinos', 'west bank and gaza']::text[], 'Asia', 'Asia occidental', true, 35.2523, 31.9308),
  ('PT', 'PRT', '620', 'Portugal', 'portugal', array['portuguesa', 'portuguese republic', 'republica portuguesa']::text[], 'Europa', 'Europa meridional', true, -8.0447, 39.599),
  ('PW', 'PLW', '585', 'Palaos', 'palaos', array['beluu er a belau', 'palau', 'republic of palau', 'republica de palau']::text[], 'Oceanía', 'Micronesia', false, 134.5, 7.5),
  ('PY', 'PRY', '600', 'Paraguay', 'paraguay', array['republic of paraguay', 'republica de paraguay', 'republica del paraguay', 'teta paraguai']::text[], 'América', 'América del Sur', true, -59.915, -22.0196),
  ('QA', 'QAT', '634', 'Catar', 'catar', array['dawlat qatar', 'estado de qatar', 'qatar', 'state of qatar']::text[], 'Asia', 'Asia occidental', true, 51.1513, 25.3156),
  ('RE', 'REU', '638', 'Reunión', 'reunion', array['isla de la reunion', 'reunion island']::text[], 'África', 'África oriental', false, 55.5, -21.15),
  ('RO', 'ROU', '642', 'Rumania', 'rumania', array['romania', 'roumania']::text[], 'Europa', 'Europa oriental', true, 24.8832, 45.8513),
  ('RS', 'SRB', '688', 'Serbia', 'serbia', array['republic of serbia', 'republica de serbia', 'republika srbija', 'srbija']::text[], 'Europa', 'Europa meridional', true, 20.8186, 44.1945),
  ('RU', 'RUS', '643', 'Rusia', 'rusia', array['federacion de rusia', 'federacion rusa', 'russia', 'russian federation']::text[], 'Europa', 'Europa oriental', true, 99.1701, 63.3021),
  ('RW', 'RWA', '646', 'Ruanda', 'ruanda', array['republic of rwanda', 'republica de rwanda', 'republique du rwanda', 'repubulika yu rwanda', 'rwanda']::text[], 'África', 'África oriental', true, 29.8698, -1.8391),
  ('SA', 'SAU', '682', 'Arabia Saudita', 'arabia saudita', array['al mamlakah al arabiyyah as suudiyyah', 'arabia saudi', 'kingdom of saudi arabia', 'reino de arabia saudita', 'saudi', 'saudi arabia']::text[], 'Asia', 'Asia occidental', true, 44.5127, 24.0696),
  ('SB', 'SLB', '090', 'Islas Salomón', 'islas salomon', array['solomon is', 'solomon islands']::text[], 'Oceanía', 'Melanesia', true, 159.1438, -7.9187),
  ('SC', 'SYC', '690', 'Seychelles', 'seychelles', array['repiblik sesel', 'republic of seychelles', 'republica de las seychelles', 'republique des seychelles']::text[], 'África', 'África oriental', false, 55.6667, -4.5833),
  ('SD', 'SDN', '729', 'Sudán', 'sudan', array['jumhuriyat as sudan', 'republic of the sudan', 'republica de sudan']::text[], 'África', 'África septentrional', true, 29.7282, 16.1219),
  ('SE', 'SWE', '752', 'Suecia', 'suecia', array['kingdom of sweden', 'konungariket sverige', 'reino de suecia', 'sweden']::text[], 'Europa', 'Europa septentrional', true, 14.9017, 62.1132),
  ('SG', 'SGP', '702', 'Singapur', 'singapur', array['republic of singapore', 'republica de singapur', 'republik singapura', 'singapore', 'singapura']::text[], 'Asia', 'Sudeste asiático', false, 103.8, 1.3667),
  ('SH', 'SHN', '654', 'Santa Elena', 'santa elena', array['saint helena', 'saint helena ascension and tristan da cunha', 'santa elena ascension y tristan de acuna', 'st helena ascension and tristan da cunha']::text[], 'África', 'África occidental', false, -5.72, -15.95),
  ('SI', 'SVN', '705', 'Eslovenia', 'eslovenia', array['republic of slovenia', 'republica de eslovenia', 'republika slovenija', 'slovenia']::text[], 'Europa', 'Europa meridional', true, 14.998, 46.0382),
  ('SJ', 'SJM', '744', 'Svalbard y Jan Mayen', 'svalbard y jan mayen', array['islas svalbard y jan mayen', 'svalbard and jan mayen', 'svalbard and jan mayen islands', 'svalbard og jan mayen']::text[], 'Europa', 'Europa septentrional', true, 15.6311, 78.3402),
  ('SK', 'SVK', '703', 'Eslovaquia', 'eslovaquia', array['republica eslovaca', 'slovak republic', 'slovakia', 'slovenska republika']::text[], 'Europa', 'Europa oriental', true, 19.2153, 48.7667),
  ('SL', 'SLE', '694', 'Sierra Leona', 'sierra leona', array['republic of sierra leone', 'republica de sierra leona', 'sierra leone']::text[], 'África', 'África occidental', true, -11.7819, 8.5485),
  ('SM', 'SMR', '674', 'San Marino', 'san marino', array['most serene republic of san marino', 'repubblica di san marino', 'republic of san marino', 'serenisima republica de san marino']::text[], 'Europa', 'Europa meridional', false, 12.4167, 43.7667),
  ('SN', 'SEN', '686', 'Senegal', 'senegal', array['republic of senegal', 'republica de senegal', 'republique du senegal']::text[], 'África', 'África occidental', true, -14.3329, 14.3821),
  ('SO', 'SOM', '706', 'Somalia', 'somalia', array['as sumal', 'federal republic of somalia', 'jamhuuriyadda federaalka soomaaliya', 'jumhuriyyat as sumal al fideraliyya', 'republic of somaliland', 'republica federal de somalia', 'somaliland', 'somalilandia']::text[], 'África', 'África oriental', true, 48.7101, 9.5749),
  ('SR', 'SUR', '740', 'Surinam', 'surinam', array['republic of suriname', 'republica de suriname', 'republiek suriname', 'sarnam', 'sranangron', 'suriname']::text[], 'América', 'América del Sur', true, -55.9391, 4.1098),
  ('SS', 'SSD', '728', 'Sudán del Sur', 'sudan del sur', array['republic of south sudan', 'republica de sudan del sur', 's sudan', 'south sudan']::text[], 'África', 'África oriental', true, 30.1869, 7.278),
  ('ST', 'STP', '678', 'Santo Tomé y Príncipe', 'santo tome y principe', array['democratic republic of sao tome and principe', 'republica democratica de santo tome y principe', 'republica democratica de sao tome e principe', 'sao tome and principe']::text[], 'África', 'África central', false, 7, 1),
  ('SV', 'SLV', '222', 'El Salvador', 'el salvador', array['republic of el salvador', 'republica de el salvador']::text[], 'América', 'Centroamérica', true, -88.8701, 13.7222),
  ('SX', 'SXM', '534', 'Sint Maarten', 'sint maarten', array['sint maarten dutch part']::text[], 'América', 'Caribe', false, -63.05, 18.0333),
  ('SY', 'SYR', '760', 'Siria', 'siria', array['republica arabe siria', 'syria', 'syrian arab republic']::text[], 'Asia', 'Asia occidental', true, 38.5362, 35.0369),
  ('SZ', 'SWZ', '748', 'Esuatini', 'esuatini', array['eswatini', 'kingdom of eswatini', 'ngwane', 'reino de eswatini', 'suazilandia', 'swatini', 'swaziland', 'umbuso weswatini', 'weswatini']::text[], 'África', 'África austral', true, 31.4085, -26.5155),
  ('TC', 'TCA', '796', 'Islas Turcas y Caicos', 'islas turcas y caicos', array['islas turks y caicos', 'turks and caicos islands']::text[], 'América', 'Caribe', false, -71.5833, 21.75),
  ('TD', 'TCD', '148', 'Chad', 'chad', array['republic of chad', 'republica de chad', 'republique du tchad', 'tchad']::text[], 'África', 'África central', true, 18.6356, 15.3065),
  ('TF', 'ATF', '260', 'Territorios Australes Franceses', 'territorios australes franceses', array['fr s antarctic lands', 'french southern and antarctic lands', 'french southern territories', 'territorio del frances tierras australes y antarticas', 'territory of the french southern and antarctic lands', 'tierras australes y antarticas francesas']::text[], 'África', 'África oriental', true, 69.553, -49.2771),
  ('TG', 'TGO', '768', 'Togo', 'togo', array['republica de togo', 'republique togolaise', 'togolese', 'togolese republic']::text[], 'África', 'África occidental', true, 1.1061, 8.7099),
  ('TH', 'THA', '764', 'Tailandia', 'tailandia', array['kingdom of thailand', 'prathet', 'ratcha anachak thai', 'reino de tailandia', 'thai', 'thailand']::text[], 'Asia', 'Sudeste asiático', true, 101.0295, 15.2765),
  ('TJ', 'TJK', '762', 'Tayikistán', 'tayikistan', array['cumhuriyi tocikiston', 'republic of tajikistan', 'republica de tayikistan', 'tajikistan', 'tocikiston']::text[], 'Asia', 'Asia central', true, 69.7058, 38.6026),
  ('TK', 'TKL', '772', 'Tokelau', 'tokelau', array['islas tokelau']::text[], 'Oceanía', 'Polinesia', false, -172, -9),
  ('TL', 'TLS', '626', 'Timor Oriental', 'timor oriental', array['democratic republic of timor leste', 'east timor', 'republica democratica de timor leste', 'republika demokratika timor leste', 'timor', 'timor leste', 'timor lorosae']::text[], 'Asia', 'Sudeste asiático', true, 125.6306, -8.8664),
  ('TM', 'TKM', '795', 'Turkmenistán', 'turkmenistan', '{}', 'Asia', 'Asia central', true, 59.3734, 39.354),
  ('TN', 'TUN', '788', 'Túnez', 'tunez', array['al jumhuriyyah at tunisiyyah', 'republic of tunisia', 'republica de tunez', 'tunisia', 'tunisian republic']::text[], 'África', 'África septentrional', true, 9.0734, 33.987),
  ('TO', 'TON', '776', 'Tonga', 'tonga', array['kingdom of tonga', 'reino de tonga']::text[], 'Oceanía', 'Polinesia', false, -175, -20),
  ('TR', 'TUR', '792', 'Turquía', 'turquia', array['republic of turkey', 'republic of turkiye', 'republica de turquia', 'turkey', 'turkiye', 'turkiye cumhuriyeti']::text[], 'Asia', 'Asia occidental', true, 35.3824, 39.1764),
  ('TT', 'TTO', '780', 'Trinidad y Tobago', 'trinidad y tobago', array['republic of trinidad and tobago', 'republica de trinidad y tobago', 'trinidad and tobago']::text[], 'América', 'Caribe', true, -61.3211, 10.4273),
  ('TV', 'TUV', '798', 'Tuvalu', 'tuvalu', '{}', 'Oceanía', 'Polinesia', false, 178, -8),
  ('TW', 'TWN', '158', 'Taiwán', 'taiwan', array['chinese taipei', 'republic of china', 'republic of china taiwan', 'republica de china', 'republica de china en taiwan', 'taipei chino', 'taiwan province of china', 'zhonghua minguo']::text[], 'Asia', 'Asia oriental', true, 120.941, 23.7532),
  ('TZ', 'TZA', '834', 'Tanzania', 'tanzania', array['jamhuri ya muungano wa tanzania', 'republica unida de tanzania', 'tanzania united republic of', 'united republic of tanzania']::text[], 'África', 'África oriental', true, 34.7747, -6.0675),
  ('UA', 'UKR', '804', 'Ucrania', 'ucrania', array['ukraine', 'ukrayina']::text[], 'Europa', 'Europa oriental', true, 31.3934, 49.1303),
  ('UG', 'UGA', '800', 'Uganda', 'uganda', array['jamhuri ya uganda', 'republic of uganda', 'republica de uganda']::text[], 'África', 'África oriental', true, 32.3602, 1.3213),
  ('UM', 'UMI', '581', 'Islas Ultramarinas de EE.UU.', 'islas ultramarinas de eeuu', array['estados unidos islas menores alejadas de', 'islas menores alejadas de ee uu', 'islas ultramarinas menores de estados unidos', 'united states minor outlying islands']::text[], 'Oceanía', 'Micronesia', false, 166.6333, 19.3),
  ('US', 'USA', '840', 'Estados Unidos', 'estados unidos', array['ee uu', 'eeuu', 'estados unidos de america', 'estados unidos de norteamerica', 'eua', 'united states', 'united states of america', 'usa']::text[], 'América', 'América del Norte', true, -99.0531, 39.4998),
  ('UY', 'URY', '858', 'Uruguay', 'uruguay', array['oriental republic of uruguay', 'republica oriental del uruguay']::text[], 'América', 'América del Sur', true, -55.9952, -32.7833),
  ('UZ', 'UZB', '860', 'Uzbekistán', 'uzbekistan', array['ozbekiston respublikasi', 'republic of uzbekistan', 'republica de uzbekistan']::text[], 'Asia', 'Asia central', true, 63.6643, 41.7422),
  ('VA', 'VAT', '336', 'Ciudad del Vaticano', 'ciudad del vaticano', array['holy see', 'holy see vatican city state', 'santa sede', 'stato della citta del vaticano', 'vatican', 'vatican city', 'vatican city state', 'vaticano']::text[], 'Europa', 'Europa meridional', false, 12.45, 41.9),
  ('VC', 'VCT', '670', 'San Vicente y las Granadinas', 'san vicente y las granadinas', array['saint vincent and the grenadines', 'san vicente y granadinas']::text[], 'América', 'Caribe', false, -61.2, 13.25),
  ('VE', 'VEN', '862', 'Venezuela', 'venezuela', array['bolivarian republic of venezuela', 'republica bolivariana de venezuela', 'venezuela bolivarian republic of']::text[], 'América', 'América del Sur', true, -64.8647, 7.3165),
  ('VG', 'VGB', '092', 'Islas Vírgenes Británicas', 'islas virgenes britanicas', array['british virgin islands', 'islas virgenes del reino unido', 'virgin islands british']::text[], 'América', 'Caribe', false, -64.6231, 18.4314),
  ('VI', 'VIR', '850', 'Islas Vírgenes de EE. UU.', 'islas virgenes de ee uu', array['islas virgenes de los estados unidos', 'united states virgin islands', 'virgin islands of the united states', 'virgin islands us']::text[], 'América', 'Caribe', false, -64.9333, 18.35),
  ('VN', 'VNM', '704', 'Vietnam', 'vietnam', array['cong hoa xa hoi chu nghia viet nam', 'republica socialista de vietnam', 'socialist republic of vietnam', 'viet nam']::text[], 'Asia', 'Sudeste asiático', true, 105.3063, 21.7529),
  ('VU', 'VUT', '548', 'Vanuatu', 'vanuatu', array['republic of vanuatu', 'republica de vanuatu', 'republique de vanuatu', 'ripablik blong vanuatu']::text[], 'Oceanía', 'Melanesia', true, 166.9403, -15.2449),
  ('WF', 'WLF', '876', 'Wallis y Futuna', 'wallis y futuna', array['territoire des iles wallis et futuna', 'territorio de las islas wallis y futuna', 'territory of the wallis and futuna islands', 'wallis and futuna']::text[], 'Oceanía', 'Polinesia', false, -176.2, -13.3),
  ('WS', 'WSM', '882', 'Samoa', 'samoa', array['estado independiente de samoa', 'independent state of samoa']::text[], 'Oceanía', 'Polinesia', false, -172.3333, -13.5833),
  ('XK', 'XKX', null, 'Kosovo', 'kosovo', array['republic of kosovo', 'republica de kosovo']::text[], 'Europa', 'Europa meridional', true, 20.8991, 42.5538),
  ('YE', 'YEM', '887', 'Yemen', 'yemen', array['al jumhuriyyah al yamaniyyah', 'republic of yemen', 'republica de yemen', 'yemeni republic']::text[], 'Asia', 'Asia occidental', true, 46.0052, 15.3001),
  ('YT', 'MYT', '175', 'Mayotte', 'mayotte', array['departamento de mayotte', 'departement de mayotte', 'department of mayotte']::text[], 'África', 'África oriental', false, 45.1667, -12.8333),
  ('ZA', 'ZAF', '710', 'Sudáfrica', 'sudafrica', array['republic of south africa', 'republica de sudafrica', 'rsa', 'south africa', 'suid afrika']::text[], 'África', 'África austral', true, 23.6699, -29.3729),
  ('ZM', 'ZMB', '894', 'Zambia', 'zambia', array['republic of zambia', 'republica de zambia']::text[], 'África', 'África oriental', true, 26.7241, -14.5945),
  ('ZW', 'ZWE', '716', 'Zimbabue', 'zimbabue', array['republic of zimbabwe', 'republica de zimbabue', 'zimbabwe']::text[], 'África', 'África oriental', true, 29.7911, -18.9144)
on conflict (iso2) do update set
  iso3 = excluded.iso3,
  numerico = excluded.numerico,
  nombre = excluded.nombre,
  nombre_normalizado = excluded.nombre_normalizado,
  alias = excluded.alias,
  continente = excluded.continente,
  subregion = excluded.subregion,
  con_geometria = excluded.con_geometria,
  lon = excluded.lon,
  lat = excluded.lat;

do $$ begin
  assert (select count(*) from public.paises) = 250, 'paises: se esperaban 250 filas (ISO 3166-1 + XK)';
end $$;
